# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-06-16 14:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50, verbose_name='类别')),
            ],
            options={
                'verbose_name': '书籍类别',
                'verbose_name_plural': '书籍类别',
            },
        ),
        migrations.CreateModel(
            name='BookList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='书名')),
                ('author', models.CharField(max_length=30, verbose_name='作者')),
                ('press', models.CharField(max_length=100, verbose_name='出版社')),
                ('num', models.IntegerField(default=0, verbose_name='库存')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=11)),
                ('image', models.ImageField(null=True, upload_to='static/images/goods/', verbose_name='图片')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_list.BookCategory', verbose_name='类别')),
            ],
            options={
                'verbose_name': '书籍清单',
                'verbose_name_plural': '书籍清单',
            },
        ),
    ]
